import{a as q,S as v,i as a}from"./assets/vendor-CIu9XFSi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",E="32802293-5821b85c58537e1609d134566";async function d(t,o=1){const i={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await q.get(B,{params:i})).data}catch(n){throw console.error("Помилка під час отримання зображень:",n.message),n}}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const o=t.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:s,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){u.innerHTML=""}function m(){f.hidden=!1}function y(){f.hidden=!0}function P(){h.hidden=!1}function g(){h.hidden=!0}const R=document.querySelector(".form"),O=document.querySelector(".search-text"),x=document.querySelector(".load-more");let c=1,l="",b=0;R.addEventListener("submit",async t=>{t.preventDefault();const o=O.value.trim();if(!o){a.warning({title:"Увага",message:"Введіть слово для пошуку!",position:"topRight"});return}$(),g(),m();try{l=o,c=1;const i=await d(l,c);if(b=i.totalHits,i.hits.length===0){a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(i.hits),L(i.hits.length)}catch{a.error({title:"Помилка",message:"Виникла проблема з отриманням даних!",position:"topRight"})}finally{y()}});x.addEventListener("click",async()=>{c+=1,m();try{const t=await d(l,c);p(t.hits),C(),L(t.hits.length)}catch{a.error({title:"Помилка",message:"Error",position:"topRight"})}finally{y()}});function C(){const t=document.querySelector(".gallery");if(!t.firstElementChild)return;const{height:o}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function L(t){c*15>=b||t<15?(g(),a.info({title:"Кінець колекції",message:"You've reached the end of search results.",position:"topRight"})):P()}
//# sourceMappingURL=index.js.map
