import{a as w,S as v,i as s}from"./assets/vendor-CIu9XFSi.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",P="32802293-5821b85c58537e1609d134566";let c=1,d="";async function p(r){r!==d&&(d=r,c=1);const i={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:c};try{const t=await w.get(S,{params:i});return c+=1,t.data}catch(t){throw console.error("Помилка під час отримання зображень:",t.message),t}}function $(){c=1}const f=document.querySelector(".gallery"),h=document.querySelector(".loader-container"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const i=r.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:n,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${t}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${L}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",i),q.refresh()}function E(){f.innerHTML=""}function y(){h.classList.add("visible")}function u(){h.classList.remove("visible")}const O=document.querySelector(".form"),R=document.querySelector(".search-text"),l=document.querySelector(".load-more");let g="";O.addEventListener("submit",async r=>{r.preventDefault();const i=R.value.trim();if(i===""){s.warning({title:"Увага",message:"Введіть слово для пошуку!",position:"topRight"});return}E(),l.hidden=!0,y();try{$(),g=i;const t=await p(i);if(t.hits.length===0){s.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}m(t.hits),t.hits.length===15&&(l.hidden=!1)}catch(t){s.error({title:"Помилка",message:"Виникла проблема з отриманням даних!",position:"topRight"}),console.error(t)}finally{u()}});l.addEventListener("click",async()=>{y();try{const r=await p(g);m(r.hits),window.scrollBy({top:window.innerHeight*.6,behavior:"smooth"}),r.hits.length<15&&(s.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l.hidden=!0)}catch(r){s.error({title:"Помилка",message:"Error",position:"topRight"}),console.error(r)}finally{u()}});
//# sourceMappingURL=index.js.map
